export const FETCH_TASKS_START = 'FETCH_TASKS_START';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAILURE = 'FETCH_TASKS_FAILURE';
export const UPDATE_TASKS = 'UPDATE_TASKS';

export const COMPLETE_TASK_START = 'COMPLETE_TASK_START';
export const COMPLETE_TASK_SUCCESS = 'COMPLETE_TASK_SUCCESS';
export const COMPLETE_TASK_FAILURE = 'COMPLETE_TASK_FAILURE';
